---
- hosts: redis
  become: yes
  gather_facts: false
  tasks:
    - name: Gather service facts
      service_facts:

    - assert:
        that: ansible_facts.services["redis.service"].state == 'running'

    - assert:
        that: ansible_facts.services["sentinel.service"].state == 'running'
